relations:
  - relation: PART_OF
    source:
      apiVersion: entities.devgraph.ai/v1
      kind: GithubRepository
      name: devgraph-dora-molecule-demo
    target:
      apiVersion: entities.devgraph.ai/v1
      kind: Workstream
      name: devgraph
